name: Update Perps Volume Data

on:
  schedule:
    - cron: '0 5 * * *'  # Run daily at 05:00 UTC
  workflow_dispatch:     # Enable manual run

jobs:
  update-perps-volume:
    runs-on: ubuntu-latest

    env:
      COINALYZE_API_KEY: ${{ secrets.COINALYZE_API_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests tqdm

      - name: Run update script
        run: python scripts/update_perps_volume.py

      - name: Commit changes (if any)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/perps_volume_data.json
          git diff --cached --quiet || git commit -m "update: add latest volume data"
          git push
